server:
  port: ${SERVER_PORT:8083}

logging:
  file:
    name: logs/log.log
  level:
    root: info

springdoc:
  swagger-ui:
    supportedSubmitMethods: "post"
    disable-swagger-default-url: true
    path: /
  pathsToMatch: /, /**
  api-docs.path: /swagger

domain.name: http://localhost